
/**
 * Array de traducciones sincronizado con la colección 'translates' en MongoDB
 * Las claves están ordenadas exactamente como aparecen en la base de datos
 */
export const arrayToTranslates = [
    "Sign off",
    "Inbox",
    "Home",
    "Admin",
    "Users",
    "Roles",
    "Templates",
    "Permissions",
    "Transactions",
    "Setting",
    "Flag config",
    "Help",
    "My account",
    "Settings",
    "Reports",
    "Permissions assigned",
    "In build",
    "Support",
    "About",
    "Contact",
    "Copyright",
    "Preview",
    "PDF",
    "Close",
    "Customers",
    "Company",
    "View PDF",
    "Previous",
    "Next",
    "Go back to list",
    "Type Time Series",
    "Mark as read",
    "System users",
    "Note",
    "Edit",
    "Status",
    "Data",
    "Participant",
    "Type",
    "Search",
    "Quick search in the panel",
    "Select a type",
    "Contract",
    "Init tour",
    "Text copied",
    "Profile",
    "Add",
    "Description",
    "Attachments",
    "Del",
    "Created by",
    "Go back",
    "Select a file",
    "Upload attachments",
    "to",
    "by",
    "at",
    "Male",
    "Female",
    "years old",
    "Database name",
    "Collection name",
    "Preload",
    "Reset",
    "DB info",
    "Entity",
    "Is active",
    "View",
    "Go to this data",
    "Title",
    "Exp Date",
    "CopyID",
    "Transactions add",
    "Click to copy ID",
    "Current status",
    "Total paid",
    "client reports",
    "Nit client",
    "Name",
    "Phone number",
    "Total debt",
    "NIT",
    "Address",
    "Manager",
    "Add client",
    "Credit",
    "Document type",
    "Document",
    "Role",
    "Add user",
    "Super admin",
    "Active",
    "Edit template",
    "Add role",
    "Category",
    "Add permission",
    "Select a category",
    "Permissions to system features",
    "Preview detail this permission",
    "Edit this permission",
    "Is activate, click for inactivate",
    "Permission templates",
    "Permissions in template",
    "All template permissions",
    "Action",
    "Permissions assigned to the template",
    "Yes to continue assigning the permission",
    "You want to perform this action.",
    "at template with name",
    "Yes",
    "is activate",
    "Flags",
    "Add config",
    "Allowed users",
    "Disallowed users",
    "Flag",
    "Sign in to your account",
    "Email address",
    "Password",
    "Forgot password",
    "Sign in",
    "Not a member",
    "Email contact",
    "Send Notification",
    "No data found",
    "Documentation API",
    "Upload a file",
    "Online",
    "Cash",
    "Upload",
    "State of the edition",
    "Other fields",
    "Edit date",
    "Go to main dashboard",
    "Managing users",
    "More info",
    "There is no data to export",
    "Is sent",
    "Notification email",
    "Notification has been sent by mail",
    "No email notifications have been sent",
    "Sending",
    "Send new password",
    "Forgot Password",
    "Accept",
    "Save config",
    "Citizenship card",
    "Identity card",
    "Foreigners identity card",
    "Military ID",
    "Civil registry",
    "UserName"
];
