import ActivityDataPage from '@/components/activity/data-page';
import { AdminCookieSettings } from '@/components/admin/cookie-settings';
import ParticipantDataPage from '@/components/participant/data-page';
import CompanyDataPage from '@/components/company/data-page';
import ConfigDataPage from '@/components/config/data-page';
import EmotionDataPage from '@/components/emotion/data-page';
import GeneralDashboardComponent from '@/components/general-dashboard';
import PolicyDataPage from '@/components/policy/data-page';
import PermissionTemplateListPage from '@/components/permissionTemplate/data-page';
import PermissionListPage from '@/components/permission/data-page';
import PreTestDataPage from '@/components/preTest/data-page';
import TestListPage from '@/components/test/test-list-page';
import CourseListPage from '@/components/course/course-list-page';
import ContactDataPage from '@/components/contact/data-page';
import FeedbackDataPage from '@/components/feedback/feedback-data-page';
import ReportsPage from '@/components/reports/reports-page';
import RoleDataPage from '@/components/role/data-page';
import UserDataPage from '@/components/user/data-page';
import BlockedIpsDataPage from '@/components/blocked-ips/blocked-ips-data-page';
import TeacherCourseList from '@/components/course/teacher-course-list';
import MyCoursesList from '@/components/enrollment/my-courses-list';
import MyParticipations from '@/components/participant/my-participations';
import MyTestResponses from '@/components/test/my-test-responses';
export const items = [
  {
    _id: '1',
    name: 'Inicio',
    href: '/general-dashboard',
    label: 'Inicio',
    color: '#EAEAEA',
    icon: 'HomeIcon',
    description: 'Ir al panel principal',
    component: GeneralDashboardComponent,
    isActive: true,
    children: [],
  },
  /*{
    _id: '7',
    name: 'reports',
    href: '/reports/dashboard-reports',
    label: 'Estadisticas',
    color: '#EAEAEA',
    description: getSafeKeyFromStorage('All reports required for monitoring'),
    icon: 'ChartBarIcon',
    component: DashboardReports,
    isActive: true,
    children: [],
  },
  {
    _id: '15',
    name: 'PreTests',
    href: '/Pretest/dashboard-Pretest',
    label: 'PreTests',
    color: '#EAEAEA',
    description: 'PreTests',
    icon: 'ClipboardListIcon',
    component: PreTestDataPage,
    isActive: true,
    children: [],
  },*/
  {
    _id: '41',
    name: 'tests',
    href: '/Test/dashboard-Test',
    label: 'Tests',
    color: '#EAEAEA',
    description: 'Gestión de Tests',
    icon: 'ClipboardListIcon',
    sidebarSerial: ['PERM-0027', 'P-EST-001', '15', 'P-DOC-004'],
    excludeRoles: ['Estudiante'],
    component: TestListPage,
    isActive: true,
    children: [],
  },
  {
    _id: '49',
    name: 'my-test-responses',
    href: '/test/my-responses',
    label: 'Mis respuestas',
    color: '#EAEAEA',
    description: 'Ver mis respuestas a tests',
    icon: 'ClipboardListIcon',
    sidebarSerial: 'P-EST-001',
    component: MyTestResponses,
    isActive: true,
    children: [],
  },
  {
    _id: '46',
    name: 'mis-cursos-docente',
    href: '/teacher/courses',
    label: 'Mis Cursos',
    color: '#EAEAEA',
    description: 'Monitoreo de cursos y estudiantes',
    icon: 'AcademicCapIcon',
    sidebarSerial: 'P-DOC-001',
    component: TeacherCourseList,
    isActive: true,
    children: [],
  },
  {
    _id: '47',
    name: 'mis-cursos-estudiante',
    href: '/enrollment/my-courses',
    label: 'Mis Cursos',
    color: '#EAEAEA',
    description: 'Ver mis cursos asignados',
    icon: 'AcademicCapIcon',
    sidebarSerial: ['P-ENROLL-004', 'P-EST-003'],
    component: MyCoursesList,
    isActive: true,
    children: [],
  },
  {
    _id: '16',
    name: 'activities',
    href: '/activities/dashboard-activities',
    label: 'Actividades',
    color: '#EAEAEA',
    description: 'Gestión de actividades',
    icon: 'PlayIcon',
    sidebarSerial: ['PERM-0007', 'P-DOC-003'],
    excludeRoles: ['Estudiante'],
    component: ActivityDataPage,
    isActive: true,
    children: [],
  },
  {
    _id: '48',
    name: 'my-participations',
    href: '/participant/my-participations',
    label: 'Mis participaciones',
    color: '#EAEAEA',
    description: 'Ver mi historial de actividades completadas',
    icon: 'ClipboardListIcon',
    sidebarSerial: 'P-EST-003',
    component: MyParticipations,
    isActive: true,
    children: [],
  },
  {
    _id: '17',
    name: 'emotions',
    href: '/emotion/emotion-table',
    label: 'Emociones',
    color: '#EAEAEA',
    description: 'Gestión de emociones',
    icon: 'EmojiHappyIcon',
    sidebarSerial: ['PERM-0011', 'P-DOC-006'],
    excludeRoles: ['Estudiante'],
    component: EmotionDataPage,
    isActive: true,
    children: [],
  },
  {
    _id: '44',
    name: 'reports',
    href: '/reports/dashboard-reports',
    label: 'Reportes',
    color: '#EAEAEA',
    description: 'Reportes de participación en actividades',
    icon: 'ChartBarIcon',
    sidebarSerial: ['PERM-0001', 'P-DOC-005'],
    component: ReportsPage,
    isActive: true,
    children: [],
  },
  {
    _id: '5',
    name: 'administracion',
    href: '#',
    label: 'Administración',
    color: '#EAEAEA',
    icon: 'OfficeBuildingIcon',
    description: 'Gestión de usuarios, participantes, instituciones y cursos',
    sidebarSerial: 'PERM-0001',
    isActive: true,
    children: [
      {
        _id: '24',
        name: 'participants',
        href: '/participant/participant-table',
        label: 'Participantes',
        color: '#EAEAEA',
        description: 'Participantes de servicios médicos',
        icon: 'UserGroupIcon',
        component: ParticipantDataPage,
        isActive: true,
      },
      {
        _id: '20',
        name: 'user',
        href: '/user/user-table',
        label: 'Usuarios',
        color: '#EAEAEA',
        description: 'Gestión de usuarios',
        icon: 'UserIcon',
        component: UserDataPage,
        isActive: true,
      },
      {
        _id: '31',
        name: 'company',
        href: '/company/company-table',
        label: 'Instituciones',
        color: '#EAEAEA',
        description: 'Más información',
        icon: 'OfficeBuildingIcon',
        component: CompanyDataPage,
        isActive: true,
      },
      {
        _id: '39',
        name: 'courses',
        href: '/course/course-table',
        label: 'Cursos',
        color: '#EAEAEA',
        description: 'Gestión de cursos educativos',
        icon: 'AcademicCapIcon',
        component: CourseListPage,
        isActive: true,
      },
    ],
  },
  {
    _id: '3',
    name: 'setting',
    href: '#',
    label: 'Configuración',
    color: '#EAEAEA',
    icon: 'CogIcon',
    description: 'Gestión de configuraciones del sistema',
    sidebarSerial: 'PERM-0039',
    isActive: true,
    children: [
      {
        _id: '32',
        name: 'role',
        href: '/role/role-table',
        label: 'Roles',
        color: '#EAEAEA',
        description: 'Gestión de roles',
        icon: 'FingerPrintIcon',
        component: RoleDataPage,
        isActive: true,
      },
      {
        _id: '33',
        name: 'permissions',
        href: '/permission/permission-table',
        label: 'Permisos',
        color: '#EAEAEA',
        description: 'Gestión de permisos individuales',
        icon: 'KeyIcon',
        component: PermissionListPage,
        isActive: true,
      },
      {
        _id: '34',
        name: 'templates',
        href: '/permissionTemplate/table',
        label: 'Plantillas',
        color: '#EAEAEA',
        description: 'Agrupar permisos en plantillas asignables a roles',
        icon: 'TemplateIcon',
        component: PermissionTemplateListPage,
        isActive: true,
      },
      {
        _id: '36',
        name: 'flags',
        href: '/config/config-table',
        label: 'Flags',
        color: '#EAEAEA',
        description: 'Más información',
        icon: 'FlagIcon',
        sidebarSerial: 'PERM-0040',
        component: ConfigDataPage,
        isActive: true,
      },
      {
        _id: '38',
        name: 'policies',
        href: '/policy/policy-table',
        label: 'Políticas',
        color: '#EAEAEA',
        description: 'Más información',
        icon: 'DocumentTextIcon',
        sidebarSerial: 'PERM-0040',
        component: PolicyDataPage,
        isActive: true,
      },
      {
        _id: '42',
        name: 'contact',
        href: '/contact/contact-table',
        label: 'Contacto',
        color: '#EAEAEA',
        description: 'Gestión de mensajes de contacto',
        icon: 'MailIcon',
        sidebarSerial: 'PERM-0040',
        component: ContactDataPage,
        isActive: true,
      },
      {
        _id: '43',
        name: 'feedback',
        href: '/feedback/feedback-table',
        label: 'Feedback',
        color: '#EAEAEA',
        description: 'Gestión de feedback y conversión a ideas',
        icon: 'AnnotationIcon',
        sidebarSerial: 'PERM-0040',
        component: FeedbackDataPage,
        isActive: true,
      },
      {
        _id: '37',
        name: 'seguridad',
        href: '/admin/cookie-settings',
        label: 'Seguridad',
        color: '#EAEAEA',
        description: 'Panel de seguridad y configuración del sistema',
        icon: 'ShieldCheckIcon',
        sidebarSerial: 'PERM-0041',
        component: AdminCookieSettings,
        isActive: true,
      },
      {
        _id: '45',
        name: 'blocked-ips',
        href: '/blocked-ips/blocked-ips-table',
        label: 'IP Bloqueadas',
        color: '#EAEAEA',
        description: 'Gestión de IPs bloqueadas por actividad sospechosa',
        icon: 'ShieldExclamationIcon',
        sidebarSerial: 'PERM-0041',
        component: BlockedIpsDataPage,
        isActive: true,
      },
    ],
  } /*
{
    "_id": "8",
    "name": "help",
    "href": "/help/help",
    "label": getSafeKeyFromStorage('Help'),
    "color": "#EAEAEA",
    "description": getSafeKeyFromStorage("More info..."),
    "icon": "QuestionMarkCircleIcon",
    "children": []
}*/,
];
