import ActivityDataPage from '@/components/activity/data-page';
import { AdminCookieSettings } from '@/components/admin/cookie-settings';
import ParticipantDataPage from '@/components/participant/data-page';
import CompanyDataPage from '@/components/company/data-page';
import ConfigDataPage from '@/components/config/data-page';
import EmotionDataPage from '@/components/emotion/data-page';
import GeneralDashboardComponent from '@/components/general-dashboard';
import PolicyDataPage from '@/components/policy/data-page';
import PermissionTemplateListPage from '@/components/permissionTemplate/data-page';
import PermissionListPage from '@/components/permission/data-page';
import PreTestDataPage from '@/components/preTest/data-page';
import TestListPage from '@/components/test/test-list-page';
import CourseListPage from '@/components/course/course-list-page';
import ContactDataPage from '@/components/contact/data-page';
import FeedbackDataPage from '@/components/feedback/feedback-data-page';
//import DashboardReports from '@/components/reports/dashboard-reports';
import RoleDataPage from '@/components/role/data-page';
import UserDataPage from '@/components/user/data-page';
import { getSafeKeyFromStorage } from '@/utils/safe-token-storage';

export const items = [
  {
    _id: '1',
    name: 'Inicio',
    href: '/general-dashboard',
    label: 'Inicio',
    color: '#EAEAEA',
    icon: 'HomeIcon',
    description: getSafeKeyFromStorage('Go to main dashboard'),
    permissionID: '4',
    component: GeneralDashboardComponent,
    isActive: true,
    children: [],
  },
  /*{
    _id: '7',
    name: 'reports',
    href: '/reports/dashboard-reports',
    label: 'Estadisticas',
    color: '#EAEAEA',
    description: getSafeKeyFromStorage('All reports required for monitoring'),
    icon: 'ChartBarIcon',
    permissionID: '8',
    component: DashboardReports,
    isActive: true,
    children: [],
  },
  {
    _id: '15',
    name: 'PreTests',
    href: '/Pretest/dashboard-Pretest',
    label: 'PreTests',
    color: '#EAEAEA',
    description: 'PreTests',
    icon: 'ClipboardListIcon',
    permissionID: '15',
    component: PreTestDataPage,
    isActive: true,
    children: [],
  },*/
  {
    _id: '41',
    name: 'tests',
    href: '/Test/dashboard-Test',
    label: 'Tests',
    color: '#EAEAEA',
    description: 'Gestión de Tests',
    icon: 'ClipboardListIcon',
    permissionID: '15',
    component: TestListPage,
    isActive: true,
    children: [],
  },
  {
    _id: '16',
    name: 'activities',
    href: '/activities/dashboard-activities',
    label: 'Actividades',
    color: '#EAEAEA',
    description: 'Actividades',
    icon: 'PlayIcon',
    permissionID: '16',
    component: ActivityDataPage,
    isActive: true,
    children: [],
  },
  {
    _id: '17',
    name: 'emotions',
    href: '/emotion/emotion-table',
    label: 'Emociones',
    color: '#EAEAEA',
    description: 'Gestión de emociones',
    icon: 'EmojiHappyIcon',
    permissionID: '8',
    component: EmotionDataPage,
    isActive: true,
    children: [],
  },
  {
    _id: '2',
    name: 'admin',
    href: '#',
    label: 'Admin',
    color: '#EAEAEA',
    icon: 'ShieldCheckIcon',
    description: getSafeKeyFromStorage('Managing users, roles and permissions'),
    permissionID: '9',
    isActive: true,
    children: [
      {
        _id: '24',
        name: 'participants',
        href: '/participant/participant-table',
        label: 'Participantes',
        color: '#EAEAEA',
        description: getSafeKeyFromStorage('Medical services participants'),
        icon: 'UserGroupIcon',
        component: ParticipantDataPage,
        isActive: true,
      },
      {
        _id: '20',
        name: 'user',
        href: '/user/user-table',
        label: 'Usuarios',
        color: '#EAEAEA',
        description: getSafeKeyFromStorage('Managing users'),
        icon: 'UserIcon',
        component: UserDataPage,
        isActive: true,
      },
    ],
  },
  {
    _id: '3',
    name: 'setting',
    href: '#',
    label: 'Configuración',
    color: '#EAEAEA',
    icon: 'CogIcon',
    description: getSafeKeyFromStorage('Managing system configurations'),
    permissionID: '10',
    isActive: true,
    children: [
      {
        _id: '31',
        name: 'company',
        href: '/company/company-table',
        label: 'Instituciones',
        color: '#EAEAEA',
        description: getSafeKeyFromStorage('More info...'),
        icon: 'OfficeBuildingIcon',
        component: CompanyDataPage,
        isActive: true,
      },
      {
        _id: '39',
        name: 'courses',
        href: '/course/course-table',
        label: 'Cursos',
        color: '#EAEAEA',
        description: 'Gestión de cursos educativos',
        icon: 'AcademicCapIcon',
        component: CourseListPage,
        isActive: true,
      },
      {
        _id: '32',
        name: 'role',
        href: '/role/role-table',
        label: 'Roles',
        color: '#EAEAEA',
        description: getSafeKeyFromStorage('Managing roles'),
        icon: 'FingerPrintIcon',
        component: RoleDataPage,
        isActive: true,
      },
      {
        _id: '33',
        name: 'permissions',
        href: '/permission/permission-table',
        label: 'Permisos',
        color: '#EAEAEA',
        description: getSafeKeyFromStorage('Managing individual permissions'),
        icon: 'KeyIcon',
        component: PermissionListPage,
        isActive: true,
      },
      {
        _id: '34',
        name: 'templates',
        href: '/permissionTemplate/table',
        label: 'Plantillas',
        color: '#EAEAEA',
        description: getSafeKeyFromStorage('Group permissions into templates assignable to roles'),
        icon: 'TemplateIcon',
        component: PermissionTemplateListPage,
        isActive: true,
      },
      {
        _id: '36',
        name: 'flags',
        href: '/config/config-table',
        label: 'Flags',
        color: '#EAEAEA',
        description: getSafeKeyFromStorage('More info...'),
        icon: 'FlagIcon',
        permissionID: '11',
        component: ConfigDataPage,
        isActive: true,
      },
      {
        _id: '38',
        name: 'policies',
        href: '/policy/policy-table',
        label: 'Políticas',
        color: '#EAEAEA',
        description: getSafeKeyFromStorage('More info...'),
        icon: 'DocumentTextIcon',
        permissionID: '11',
        component: PolicyDataPage,
        isActive: true,
      },
      {
        _id: '42',
        name: 'contact',
        href: '/contact/contact-table',
        label: 'Contacto',
        color: '#EAEAEA',
        description: 'Gestión de mensajes de contacto',
        icon: 'MailIcon',
        permissionID: '11',
        component: ContactDataPage,
        isActive: true,
      },
      {
        _id: '43',
        name: 'feedback',
        href: '/feedback/feedback-table',
        label: 'Feedback',
        color: '#EAEAEA',
        description: 'Gestión de feedback y conversión a ideas',
        icon: 'AnnotationIcon',
        permissionID: '11',
        component: FeedbackDataPage,
        isActive: true,
      },
      {
        _id: '37',
        name: 'administración',
        href: '/admin/cookie-settings',
        label: 'Administración',
        color: '#EAEAEA',
        description: 'Panel de administración de ',
        icon: 'ShieldExclamationIcon',
        permissionID: '12',
        component: AdminCookieSettings,
        isActive: true,
      },
    ],
  } /*
{
    "_id": "8",
    "name": "help",
    "href": "/help/help",
    "label": getSafeKeyFromStorage('Help'),
    "color": "#EAEAEA",
    "description": getSafeKeyFromStorage("More info..."),
    "icon": "QuestionMarkCircleIcon",
    "children": []
}*/,
];
